name: Upload to GCS
'on':
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          version: 342.0.0
          service_account_email: '${{ secrets.GCP_SA_EMAIL }}'
          service_account_key: '${{ secrets.GCP_SA_KEY }}'
          export_default_credentials: true
      - name: Upload object to GCS
        run: >-
           gsutil cp index.html gs://github-action-bucket/           
